### ISSUE TITLE
New Build Version Sigsevs When Changing Resolution

### ISSUE THREAD

**Issue by toddoestuff** [Indev450/SRB2Kart-Saturn#124]
The title should speak for itself. _The game crashes whenever I change the resolution at the beginning of a game_. If this helps, I play on the **A.R.A US server with DriftNitro on** and it seems to be a consistent occurrence there. The crash log:

**_EDIT:_** It appears to happen in general and isn't server specific.
```
Compiled: Apr  1 2024 17:25:06, commit 8ed8182a, branch Saturn-Next
Game map: MAPW7
Time of crash: Tue Apr 02 11:03:07 2024

Caused by: SIGSEGV - segment violation
Backtrace:
00000001401D89C2 _gnu_exception_handler
00007FF869FBCA05 register_frame_ctor
00007FF869FD23AE register_frame_ctor
00007FF869F814B3 register_frame_ctor
00007FF869FD0EBD register_frame_ctor
000000014018DFCB HWR_DrawMD2
0000000140186180 HWR_DrawSprites
00000001401893DE HWR_RenderViewpoint
000000014018AB65 HWR_RenderFrame
000000014000365F D_SRB2Loop
00000001400016C0 SDL_main
00000001401D93D5 main_getcmdline
00000001401D7C23 main
000000014000133F __tmainCRTStartup
0000000140001116 WinMainCRTStartup
00007FF868967343 register_frame_ctor
00007FF869F826B0 register_frame_ctor
FFFFFFFFFFFFFFFF ???
```

**Comment by alufolie91** [comment]
was smth introduced in https://github.com/Indev450/SRB2Kart-Saturn/commit/62b058c9fbfde2918e8ced85297ec680ab7c24ee
nothing significant so will just revert the palette part
will push out a hotfix soon with this issue fixed
thank you much!
