### ISSUE TITLE
Miscolored textures in Software renderer

### ISSUE THREAD

**Issue by JugadorXEI** [Indev450/SRB2Kart-Saturn#35]
If playing using the `-software` renderer, some textures (apparently related to transparency) are entirely miscolored.

Every time I load the game, the textures seem to be differently colored. Maybe it is some sort of memory leak or corruption somewhere?

Tested this by loading [ChronoShift Track Pack's ChronoShift](https://mb.srb2.org/addons/chronoshift-track-pack.5339/reviews) level.

Saturn Software:
![kart0069](https://github.com/Indev450/SRB2Kart-Saturn/assets/1565198/f576287a-5b4f-473c-9e2d-08b89fc1ecfc)
![kart0072](https://github.com/Indev450/SRB2Kart-Saturn/assets/1565198/a5368445-90bb-48a5-ac8f-f65039b30243)

Vanilla Software:
![kart0070](https://github.com/Indev450/SRB2Kart-Saturn/assets/1565198/fa4cded3-c794-4dd3-9f6b-3d4d6cc4edbc)
![kart0073](https://github.com/Indev450/SRB2Kart-Saturn/assets/1565198/1bbcfc10-1cd3-46b4-be84-b3262b13d346)

**Comment by Indev450** [comment]
Hm might be something with uninitialized memory

**Comment by alufolie91** [comment]
whoops didnt think git would close this automatically
anyways seems like screwing with the extrabytes/alignbits in the Zone Memory Allocations somehow broke this
