### ISSUE TITLE
Player Rotation When Sliptiding is ignored

### ISSUE THREAD

**Issue by Xelork** [Indev450/SRB2Kart-Saturn#82]
![kart0015](https://github.com/Indev450/SRB2Kart-Saturn/assets/101120856/b86daf3e-1afc-416c-9ffb-264f77d96772)

i want to turn it off but cant

**Comment by alufolie91** [comment]
good catch!
seems like we forgotten to add the toggle code to software renderer sprites
will be fixed in the next update c:
