### ISSUE TITLE
Saturn's Flatpak working directory behavior

### ISSUE THREAD

**Issue by MeixDev** [Indev450/SRB2Kart-Saturn#85]
Hey!

Sorry if this isn't the most appropriate way to give feedback on this.

I've been using the Galaxy builds until now, also from their Flatpak builds, but wanted to move out to Saturn. However, there seems to be some issues about how the working directy of the Saturn build is handled.

On Galaxy, launching from a folder containing `KC_Character.pk3` and executing with `-file KC_Character.pk3` in the CLI worked perfectly well. It isn't the case on Saturn, which seems to keep searching for files only in its extra/ folder, where the *.kart files and bonuschars are located ?

I couldn't give much pointers as to why both builds would work differently on that aspect, but it would be lovely if it was possible to change it.

**Comment by Indev450** [comment]
Tested both galaxy and saturn, they both can't load files from home directory (tested from there) unless started with `--filesystem=home` flag. Maybe you gave extra permission to galaxy back then?

**Comment by MeixDev** [comment]
Hey Indev!

I must have done something back then in that case. I don't have any overrides on galaxy for the filesystem so I must have missed something elsewhere.

I may have installed galaxy with my `srb2kart` user and saturn with `root` though. I will try further things and come back to you.

Thanks for the answer!

**Comment by MeixDev** [comment]
Hey Indev!

I indeed did something I absolutely forgot, and the force of habit made me not check until now. My `~/.srb2kart` folder was a symbolic link to the `~/.var/app/org.srb2.SRB2Kart-galaxy/.srb2kart`. Makes sense why it wouldn't work with Saturn, duh.

I really apologize for the useless issue. Should have scratched my head around it for a bit longer.

Thanks for everything there, take care!

**Comment by Indev450** [comment]
It's alright, glad this is resolved now :)
